@startuml
|QConnectBase|
start
while (match_try exceeded?) is (no)
   :Start timeout timer;
   while (timeout reached?) is (no)
      :Read message from connection;
      if (fetch_block?) then (false    )
            if (Message matches the search_pattern?) then (yes)
               :Return message;
               stop
            endif
      else (    true)
            if (filter_pattern defined?) then (yes    )
               if (Message matches filter_pattern?) then (yes  )
                  :Store message in queue;
               else (  no)
                  :Discard message;
               endif
            else (    no)
               :Store message in queue;
            endif

            if (Most recent stored message matches the eob_pattern?) then (yes)
               :Stop waiting for further messages;
               if (Any of the lines in queue match the search_pattern?) then (yes   )
                  :Return list of queued messages;
                  stop
               else (   no)
                  :Return empty list;
                  stop
               endif
            endif
      endif
   endwhile
   :Retry to send command;
endwhile
:Verify failed;
stop
@enduml
